### ISSUE TITLE
代码运行出现bug

### ISSUE THREAD

**Issue by Foxalter** [FirstJavaMaster/AzurLaneScripts#10]
报错信息如下:
Traceback (most recent call last):
  File "F:/workspace/Python/AzurLaneScripts-master(1)/AzurLaneScripts-master/bin/MainPageWatcher.py", line 50, in <module>
    run()
  File "F:/workspace/Python/AzurLaneScripts-master(1)/AzurLaneScripts-master/bin/MainPageWatcher.py", line 10, in run
    notice_loc = adb.get_location('temp_images/daily-task/notice.png')
  File "F:\workspace\Python\AzurLaneScripts-master(1)\AzurLaneScripts-master\common\AutoAdb.py", line 39, in get_location
    res = cv2.matchTemplate(sp_gray, temp_gray, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:588: error: (-215:Assertion failed) corr.rows <= img.rows + templ.rows - 1 && corr.cols <= img.cols + templ.cols - 1 in function 'cv::crossCorr

这个是不是没有截到屏？

**Comment by FirstJavaMaster** [comment]
是的，这个错常见于没有截到屏或者模板文件、截图文件路径有误的时候。

MainPageWatcher.py 还是个半成品，可能里面有逻辑错误；建议先不要使用
